### ISSUE TITLE
Add default partner admin intro language

### ISSUE THREAD

**Issue by michaelwheeler** [academic-innovation/frontend-app-mogc-partners#56]
Add default text below the organization or partnership name.

![Image](https://github.com/academic-innovation/frontend-app-mogc-partners/assets/763388/9b28fbed-7049-4051-ac1b-19cc81a24fe0)

**Comment by Wattsun64** [comment]
Does this language get added within the `PartnerAdmin.jsx` file?

**Comment by michaelwheeler** [comment]
> Does this language get added within the `PartnerAdmin.jsx` file?

I think on all pages with a partner name heading, but @sophiazumich can say for sure.

**Comment by sophiazumich** [comment]
Yes, I believe we decided with Monica that this is the heading/intro section on all pages. I think in the future, we may allow this to be a customizable area for partner admin (pending interest).

**Comment by Wattsun64** [comment]
@michaelwheeler is that referring to the `PartnerName.jsx` component?
